packaging: Bump to 1.8.0
Drop downstream changes :

error: could not apply eb16049... downstream: Hack to allow selecting a default output
error: could not apply be5d1bb... Added string conversion utility functions
error: could not apply 4d487b4... shell: fix various interactions with the minimized state
error: could not apply 320a8d7... shell: update pointer focus when surface is minimized.
error: could not apply 1e91d6f... Use WESTON_CONFIG env. for reading config file
error: could not apply 2c5d46c... Fixed weston transfromation problem
error: could not apply 2ddf1b5... string buffer can have a newline character

Change-Id: I9511d5e04648af3379cc75b39b6916e111338add
Signed-off-by: Philippe Coval <philippe.coval@open.eurogiciel.org>